        OPEN "weather.txt" FOR INPUT AS #1
LECTURA:
        IF EOF(1) THEN GOTO FINARCH
	LINE INPUT #1, A$
	IF MID$(A$,3,5)="33591" THEN
		LINEA1$ = A$
		LINE INPUT #1, A$
		LINEA2$ = A$
	END IF	
	GOTO LECTURA
	PRINT
FINARCH:
	CLOSE #1
	LINEA1$ = "1 26536U" + RIGHT$(LINEA1$,LEN(LINEA1$)-8)
	LINEA2$ = "2 26536 " + RIGHT$(LINEA2$,LEN(LINEA2$)-8)
	V = 0
	FOR I = 1 TO LEN(LINEA1$)-1
		VALOR$ = MID$(LINEA1$,I,1)
		IF VALOR$ >= "0" AND VALOR$ <="9" THEN V = V + ASC(VALOR$)-48
		IF VALOR$ = "-" THEN V = V + 1
	NEXT I
	LINEA1$=LEFT$(LINEA1$,LEN(LINEA1$)-1) + RIGHT$(STR$(V MOD 10),1)
	V = 0
	FOR I = 1 TO LEN(LINEA2$)-1
		VALOR$ = MID$(LINEA2$,I,1)
		IF VALOR$ >= "0" AND VALOR$ <="9" THEN V = V + ASC(VALOR$)-48
		IF VALOR$ = "-" THEN V = V + 1
	NEXT I
	LINEA2$=LEFT$(LINEA2$,LEN(LINEA2$)-1) + RIGHT$(STR$(V MOD 10),1)
	OPEN "weather.txt" FOR INPUT AS #1
	OPEN "weather1.txt" FOR OUTPUT AS #2
LECTURA1:
	IF EOF(1) THEN GOTO CERRAR
	LINE INPUT #1, A$
	IF MID$(A$,3,5)="33591" THEN
		PRINT #2,LINEA1$
		PRINT #2,LINEA2$
		LINE INPUT #1,A$
	ELSE
		PRINT #2,A$
	END IF
	GOTO LECTURA1
CERRAR:
	CLOSE #1,#2
	COMANDO$ = "COPY weather1.txt weather.txt"
	SHELL COMANDO$	
END
